name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        arch: [arm, thumb2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build requirements
      run: sudo apt-get install -y binutils-multiarch-dev=2.34-*
    - name: make
      run: ARCH=${{ matrix.arch }} LIBS="-lbfd-2.34-multiarch" make
    - name: smoketest
      run: ./ldnxflat || ./mknxflat || ./readnxflat || true
    - name: test with data
      if: ${{ matrix.arch == 'thumb2' }}
      run: |
        ./mknxflat -o hello-thunk.S test-data/thumb/hello.r1
        ./ldnxflat -e main -s 2048 -o hello test-data/thumb/hello.r2
        ./readnxflat -a hello
    - name: clean
      run: make clean

  static-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'nxflat'
    - name: build requirements
      run: sudo apt-get install -y wget gcc make xz-utils libz-dev
    - name: Prepair Sources
      run: |
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.xz
        tar xf binutils-2.36.tar.xz
        mkdir out
        export PREFIX=$(realpath out)
    - name: Build BFD
      run: |
        pushd binutils-2.36
        ./configure --prefix=$PREFIX --target=arm-elf  --enable-install-libbfd --enable-install-libiberty --disable-plugins
        make all-libiberty all-bfd
        make install-libiberty install-bfd
        popd
    - name: Build NxFlat
      run: |
        pushd nxflat
        LDFLAGS="-L$PREFIX/lib -L$PREFIX/x86_64-pc-linux-gnu/arm-elf/lib" \
        CFLAGS="-I$PREFIX/include -I$PREFIX/x86_64-pc-linux-gnu/arm-elf/include" \
        LIBS="-static -lbfd -lz -liberty" \
        make
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ldnxflat
          mknxflat
          readnxflat
    - name: Smoke Test
      run: ./ldnxflat || ./mknxflat || ./readnxflat || true

