name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: false
    strategy:
      matrix:
        arch: [arm, thumb2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build requirements
      run: sudo apt-get install -y binutils-multiarch-dev=2.34-*
    - name: make
      run: ARCH=${{ matrix.arch }} LIBS="-lbfd-2.34-multiarch" make
    - name: smoketest
      run: ./ldnxflat || ./mknxflat || ./readnxflat || true
    - name: test with data
      if: ${{ matrix.arch == 'thumb2' }}
      run: |
        ./mknxflat -o hello-thunk.S test-data/thumb/hello.r1
        ./ldnxflat -e main -s 2048 -o hello test-data/thumb/hello.r2
        ./readnxflat -a hello
    - name: clean
      run: make clean

  static-build:
    if: false
    runs-on: ubuntu-latest
    env:
      PREFIX: ${{ github.workspace }}/out
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'nxflat'
    - name: build requirements
      run: sudo apt-get install -y wget gcc make xz-utils libz-dev
    - name: Prepair Sources
      working-directory: ${{ github.workspace }}
      run: |
        wget --quiet https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.xz
        tar -xvf binutils-2.36.tar.xz
    - name: Build BFD
      working-directory: binutils-2.36
      run: |
        ./configure --prefix=$PREFIX --target=arm-elf  --enable-install-libbfd --enable-install-libiberty --disable-plugins
        make all-libiberty all-bfd
        make install-libiberty install-bfd
    - name: Build NxFlat
      working-directory: nxflat
      run: |
        LDFLAGS="-L$PREFIX/lib -L$PREFIX/x86_64-pc-linux-gnu/arm-elf/lib" \
        CFLAGS="-I$PREFIX/include -I$PREFIX/x86_64-pc-linux-gnu/arm-elf/include" \
        LIBS="-static -lbfd -lz -liberty" \
        make
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: linux-static
        path: |
          nxflat/ldnxflat
          nxflat/mknxflat
          nxflat/readnxflat
    - name: Smoke Test
      working-directory: nxflat
      run: ./ldnxflat || ./mknxflat || ./readnxflat || true

  static-win-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'nxflat'
    - name: build requirements
      uses: msys2/setup-msys2@v2
      with:
        install: wget tar texinfo diffutils make libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-libzip 
    - name: Prepair Sources
      working-directory: ${{ github.workspace }}
      run: |
        wget --quiet https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.gz
        tar -xf binutils-2.36.tar.gz
    - name: Build BFD
      working-directory: binutils-2.36
      run: |
        ./configure --target=arm-elf  --enable-install-libbfd --enable-install-libiberty --disable-plugins
        make all-libiberty all-bfd
        make install-libiberty install-bfd
    - name: Build NxFlat
      working-directory: nxflat
      run: |
        LDFLAGS="-L/mingw64/x86_64-w64-mingw32/arm-elf/lib" \
        CFLAGS="-I/mingw64/x86_64-w64-mingw32/arm-elf/include" \
        LIBS="-static -lbfd -lz -liberty" \
        make
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: windows-static
        path: |
          nxflat/ldnxflat
          nxflat/mknxflat
          nxflat/readnxflat
    - name: Smoke Test
      working-directory: nxflat
      run: ./ldnxflat || ./mknxflat || ./readnxflat || true

